#Generated by Kenenl.rand function.
#with no arguments ,it return a pseudorandom Float greater than or equal to 0.0 and less than 1.0.
puts rand
puts rand
puts rand(100)
puts rand(100)
 #if you need replaceable sequence of pseudorandom numbers ,seed the random numbers generator with known numbers.
 puts srand
 print [rand(100),rand(100)]
 puts srand(0)
 print [rand(100),rand(100)]
